name: Run Tests

on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Create build directory
       run: mkdir build && cd build

     - name: CMake Configure
       run: cmake ../

     - name: Build project
       run: make -j4

     - name: Run tests
       run: ctest -j2
