name: Run Tests

on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Create build directory
       run: mkdir build

     - name: CMake Configure
       run: cmake -B build 

     - name: Build project
       working-directory: ${{github.workspace}}/build
       run: make -j4

     - name: Run tests
       working-directory: ${{github.workspace}}/build
       run: ctest -j2
    
     - name: Determine changed files
       id: changed_files
       run: echo "::set-output name=files_changed::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

     - name: Store changed files
       id: store_changed_files
       run: echo "Changed files- ${{ steps.changed_files.outputs.files_changed }}"

